// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenCRMOptModels;

#nullable disable

namespace OpenCRMOptModels.Migrations
{
    [DbContext(typeof(OptDbContext))]
    partial class OptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenCRMOptModels.Lotti", b =>
                {
                    b.Property<long>("LottoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LottoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LottoId"));

                    b.Property<int>("Modello")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.HasKey("LottoId");

                    b.HasIndex("Modello");

                    b.ToTable("Lotti", (string)null);
                });

            modelBuilder.Entity("OpenCRMOptModels.Macchine", b =>
                {
                    b.Property<int>("MacchineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MacchineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MacchineId"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MacchineId");

                    b.ToTable("Macchine", (string)null);
                });

            modelBuilder.Entity("OpenCRMOptModels.ModelliLotti", b =>
                {
                    b.Property<int>("ModelloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModelloID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelloId"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MacchineCompatibili")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ModelloId");

                    b.ToTable("ModelliLotti", (string)null);
                });

            modelBuilder.Entity("OpenCRMOptModels.Lotti", b =>
                {
                    b.HasOne("OpenCRMOptModels.ModelliLotti", "ModelloNavigation")
                        .WithMany("Lottis")
                        .HasForeignKey("Modello")
                        .IsRequired()
                        .HasConstraintName("FK_Lotti_Modelli");

                    b.Navigation("ModelloNavigation");
                });

            modelBuilder.Entity("OpenCRMOptModels.ModelliLotti", b =>
                {
                    b.Navigation("Lottis");
                });
#pragma warning restore 612, 618
        }
    }
}
